---
# tasks file for roles/database

- name: Create Database
  docker_container:
      name: database
      image: postgres:12.0-alpine
      state: started
      networks:
          - name: global_network
      env:
          POSTGRES_PASSWORD: takimapass
          POSTGRES_USER: takima
          POSTGRES_DB: SchoolOrganisation
