git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
  - stage: "Build and Test"
    language: java
    jdk: oraclejdk11
    before_script:
      - cd sample-application-backend
    script:
      - echo "Maven build"
      - echo "Run test coverage and Quality Gate"
  - stage: "Build and Test"
    language: node.js
    node_js: "12.20"
    before_script:
      - cd sample-application-frontend
    script:
      - echo "NPM install and build"
  - stage: "Package"
    before_deploy:
      - cd sample-application-backend
      - echo "Docker build ..."
      - docker pull postgres:12.0-alpine
      - docker run --rm --name database -e POSTGRES_PASSWORD=takimapass -e POSTGRES_USER=takima -e POSTGRES_DB=SchoolOrganisation postgres:12.0-alpine
      - docker build -t $DOCKER_USERNAME/backend .
      - echo "Docker login ..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Docker push ..."
      - docker tag backend $DOCKER_USERNAME/backend:latest
      deploy:
        provider: script
        script: docker push $DOCKER_USERNAME/backend
        on:
          branch: develop
  - stage: "Package"
    before_deploy:
      - cd sample-application-frontend
      - echo "Docker build ..."
      - docker build -t $DOCKER_USERNAME/frontend .
      - echo "Docker login ..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Docker push ..."
    deploy:
        provider: script
        script: docker push $DOCKER_USERNAME/frontend
        on:
          branch: develop
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"
services:
  - docker