git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
  - stage: "Build and Test"
    language: java
    jdk: oraclejdk11
    before_script:
      - cd sample-application-backend
    script:
      - echo "Maven build"
      - echo "Run test coverage and Quality Gate"
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=lucianoBrd_DevOpsTP2
  - stage: "Build and Test"
    language: node.js
    node_js: "12.20"
    before_script:
      - cd sample-application-frontend
    script:
      - echo "NPM install and build"
  - stage: "Package"
    if: branch = develop
    before_script:
      - cd sample-application-backend
    script:
      - echo "Docker build ..."
      - docker build -t $DOCKER_USERNAME/backend .
      - echo "Docker login ..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Docker push ..."
      - docker push $DOCKER_USERNAME/backend
  - stage: "Package"
    if: branch = develop
    before_script:
      - cd sample-application-frontend
    script:
      - echo "Docker build ..."
      - docker build -t $DOCKER_USERNAME/frontend .
      - echo "Docker login ..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - echo "Docker push ..."
      - docker push $DOCKER_USERNAME/frontend
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"
services:
  - docker
addons:
  sonarcloud:
    organization: "lucianobrd"
    token:
      secure: "$SONAR_TOKEN"